lrn_templates/basic_app/urls.py
from django.urls import path, include
from basic_app import views


#template tagging
app_name = 'basic_app'

urlpatterns = [
    path('relative/',views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

lrn_templates/lrn_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

lrn_templates/basic_app/models.py
from django.db import models

# Create your models here.

lrn_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number': 100}
    return render(request,'basicapp/index.html', context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_template.html')

lrn_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block%}
      <!--Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

lrn_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h1>This is index.html page showing</h1>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>


  {% endblock%}

lrn_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHERS</h1>
    <h2>This is example of template inheritance!</h2>

  {% endblock %}

lrn_templates/templates/basicapp/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE</h1>
    <a href="{% url 'basic_app:other' %}">The Other page</a>
    <a href="{% url 'admin:index' %}">Link to Admin</a>
    <a href="{% url 'index' %}">Link to INDEX</a>

  </body>
</html>